# Generated by Django 5.1.2 on 2024-10-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_external_id_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table=None,
        ),
    ]
