# Generated by Django 5.1.2 on 2024-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurant_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
