# Generated by Django 5.1.2 on 2024-11-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_menuitem_reviewtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='portion_size',
            field=models.IntegerField(default=0),
        ),
    ]
