# Generated by Django 5.1.2 on 2024-11-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_menuitem_reviewtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewtable',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='review_rating_cat',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='review_rating_ovr',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='review_scale_cat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='review_scale_ovr',
            field=models.IntegerField(null=True),
        ),
    ]
